binary-ghc-args:
- -O
- -threaded
module-template: ! 'module MODULE_NAME where

'
extensions:
  TemplateHaskell: true
  CPP: true
environment: ghc-7.8-stable-14.09
auto-hidden: []
cabal-file: project.cabal
version: 1
extra-packages: ! 'Hackage: QuickCheck 2.8'
ghc-args:
- -DTEST
excluded-modules: []
